= v10.0.8 vs. v10.0.7 comparison

== new

* (ok) Creating an SMS server connection - /mga/server_connections/sms/v1
* (ok) Deleting an SMS server connection
* (ok) Modifying an SMS server connection
* (ok) Export a Kerberos Keyfile
* (ok) Retrieve a particular audit configuration - /iam/access/v8/audit/{audit_id}
* Update a particular audit configuration - /iam/access/v8/audit/{audit_id}
* Update all audit configurations
* (ok) Retrieve the list of trace components and the tracing status - /isam/tracing?full_list=true
* (ok) Retrieving a list of all SMS server connections
* (ok) Retrieving an SMS server connection
* (ok) Setting multiple tuning parameters - new parameter `require_mtls`

== changes

* Authentication_and_Context_based_access_configuration_for_a_reverse_proxy_instance.xml - new parameters `enable_mtls` and `mutual_key_label`
* (ok) Create an API protection definition - new parameter `includeIssInAuthResp`
* (ok) Update a specified API protection definition - new parameter `includeIssInAuthResp`
* (ok) Creating_a_certificate_database.xml - new parameter `serial_number`
* (ok) Deploy Changes - new query argument `publish` /isam/pending_changes?publish=false
* (ok) Retrieving details for the configured Luna Safenet network HSM devices - new parameter `hsm.serialnumber`
* (ok) Retrieving the current authentication configuration - number of new parameters starting with `oidc_` and `enable_tokenmapping` and `tokenmapping_script`
* (ok) Updating the current authentication configuration - number of new parameters starting with `oidc_` and `enable_tokenmapping` and `tokenmapping_script`
* (ok) Retrieving the SSL certificate database details - new parameter `hsm.serialnumber`

* (ok) Updating a network certificate database - new parameter `serial_number`
* (ok) OAuth configuration for a reverse proxy instance - new parameter `enable_mtls` and `mutual_key_label`

== critical changes

== Obsolete


== No changes necessary
* (ok) Local Federation configuration for a reverse proxy instance - new parameter `enable_mtls` and `mutual_key_label`
* (ok) MMFA configuration for a reverse proxy instance - new parameter `enable_mtls` and `mutual_key_label`
* (ok) Retrieving a list of all currently tuned runtime parameters - new parameter `require_mtls`
* (ok) Retrieve a list of API protection definitions - new parameter `includeIssInAuthResp`
* (ok) Retrieve a specific API protection definition - new parameter `includeIssInAuthResp`
* (ok) Create an SMTP server connection - new parameters `requestParameters`, `successReturnCode`, `responseBodyRegex`
* (ok) Modifying an SMTP server connection - new parameters `requestParameters`, `successReturnCode`, `responseBodyRegex`
* (ok) Retrieving a list of all server connections - new json `sms`,  new parameters `runtimeServerConnectionSMSProperties`, requestParameters`, `successReturnCode`, `responseBodyRegex`
* (ok) Retrieving a list of all SMTP server connections - new parameters `requestParameters`, `successReturnCode`, `responseBodyRegex`
* (ok) Retrieving an SMTP server connection - new parameters `requestParameters`, `successReturnCode`, `responseBodyRegex`
* (ok) Retrieve the current audit configuration - /iam/access/v8/audit/
* (ok) Retrieving the complete list of SCIM configuration settings -  new json `mappings`, with keys `scim_attribute` and `source`
* (ok) Retrieving the current Verify Access user SCIM configuration settings - new json `mappings`, with keys `scim_attribute` and `source`
* (ok) Updating the Verify Access user SCIM configuration settings - new json `mappings`, with keys `scim_attribute` and `source`
* (ok) Updating the complete SCIM configuration settings - new json `mappings`, with keys `scim_attribute` and `source`