= v11.0.0 vs v10.0.8 comparison

== new

* (ok) Creating a JDBC server connection - mssql new db type
* (ok) Modifying a JDBC server connection - mssql new db type
* (ok) Retrieving a JDBC server connection - mssql new db type
* (ok) Retrieving a list of all JDBC server connections - mssql new db type
* (ok) Export the Configuration Database - mssql new type
* (ok) Export the Runtime Database - mssql new type
* (ok) Importing a personal certificate into a certificate database - new parameter `label`
* (ok) Retrieve the current cluster configuration - mssql new type
* (ok) Retrieving a list of all currently tuned runtime parameters - new parameters `inbound_keystore`, `inbound_keystore_label`, `inbound_truststore`
* (ok)Setting multiple tuning parameters - new parameters `inbound_keystore`, `inbound_keystore_label`, `inbound_truststore`
* (ok) Retrieving the administrator settings - new parameter `jsVersion`
* (ok) Updating the administrator settings - new parameter `jsVersion`

== changes

* Create a FIDO2 Relying Party - new parameter `compoundAttestationAllValid`, `ctsProfileMatch`. `jsonPolicyCondition` is now optional
* Update a specific FIDO2 Relying Party - new parameter `compoundAttestationAllValid`, `ctsProfileMatch`. `jsonPolicyCondition` is now optional
* (ok) Create a new cluster configuration - support for mssql (new parameters) for both hvdb and configdb
* (ok) Update the current cluster configuration - support for mssql (new parameters) for both hvdb and configdb
* (ok) Create Registry Authentication - new parameter `ca`
* (ok) Update Container Registry Authentication - new parameters `ca`, `proxy_host`, `proxy_port`, `proxy_user`, `proxy_pass`, `proxy_schema`
* various passwords now state what characters are supported
* (ok) Get information about the latest available update - renamed isva -> ivia
* (ok) Get information about the currently installed version - renamed isva -> ivia
* (ok) Retrieving a list of firmware settings - renamed isva -> ivia
* Retrieve a list of FIDO2 Relying Parties - new parameters `compoundAttestationAllValid`, `ctsProfileMatch`
* Retrieve a specific FIDO2 Relying Party - new parameters `compoundAttestationAllValid`, `ctsProfileMatch`
* Retrieve a list of policies (Full JSON API) - `jsonPolicyCondition` is optional now
* Retrieve a specific policy (Full JSON API) - `jsonPolicyCondition` is optional now
* Update a specified policy (Full JSON API) - `jsonPolicyCondition` is optional now

* new federated sso / oidc options for management authentication -> see 10.0.8 actually

== critical changes

* Create a push notification registration - `server_key` renamed to `service_account_json` (firebase)
* Retrieve a push notification registration - `server_key` renamed to `service_account_json` (firebase)
* Update a push notification registration- `server_key` renamed to `service_account_json` (firebase)
* Create Registry Authentication - `repoAuthCreateJsonRequest` renamed to `repoAuthJsonRequest`
* Retrieving a list of all server connections - renamed type `runtimeServersISVARuntimeJsonRsp` to `runtimeServersIVIARuntimeJsonRsp` (not sure if this is a big deal)
* Retrieving a list of all server connections - renamed type `runtimeServerConnectionISVARuntimeProperties` to `runtimeServerConnectionIVIARuntimeProperties` + mssql
* Retrieving the complete list of SCIM configuration settings - renamed type `scimISVAUserJsonResponse` to `scimIVIAUserJsonResponse`
* Retrieving the complete list of SCIM configuration settings - renamed type `scimISVAUserMappings` to `scimIVIAUserMappings`
* Updating the complete SCIM configuration settings - renamed type `scimISVAUserJsonResponse` to `scimIVIAUserJsonResponse`
* Updating the complete SCIM configuration settings - renamed type `scimISVAUserMappings` to `scimIVIAUserMappings`

* Update Container Registry Authentication - renamed `host` to `registry` - INCORRECT DOCUMENTATION

== wrongly marked critical

* (no change required) Create a push notification registration - `server_key` renamed to `service_account_json` (firebase)
* (no change required) Retrieve a push notification registration - `server_key` renamed to `service_account_json` (firebase)
* (no change required) Update a push notification registration- `server_key` renamed to `service_account_json` (firebase)
* (no change required) Create Registry Authentication - `repoAuthCreateJsonRequest` renamed to `repoAuthJsonRequest`
* (no change required) Retrieving a list of all server connections - renamed type `runtimeServersISVARuntimeJsonRsp` to `runtimeServersIVIARuntimeJsonRsp` (not sure if this is a big deal)
* (no change required) Retrieving a list of all server connections - renamed type `runtimeServerConnectionISVARuntimeProperties` to `runtimeServerConnectionIVIARuntimeProperties` + mssql
* (no change required) Retrieving the complete list of SCIM configuration settings - renamed type `scimISVAUserJsonResponse` to `scimIVIAUserJsonResponse`
* (no change required) Retrieving the complete list of SCIM configuration settings - renamed type `scimISVAUserMappings` to `scimIVIAUserMappings`
* (no change required) Updating the complete SCIM configuration settings - renamed type `scimISVAUserJsonResponse` to `scimIVIAUserJsonResponse`
* (no change required) Updating the complete SCIM configuration settings - renamed type `scimISVAUserMappings` to `scimIVIAUserMappings`


== Obsolete